"""Shared LLM client protocol for all pipeline stages.

This module defines the interface that LLM clients must implement.
It lives under bioscancast/llm/ (not under insight/) because future
stages (forecasting, etc.) will reuse it.

TODO (follow-up PR): migrate the local LLMClient protocol in
bioscancast/filtering/llm_filter.py to use this shared protocol.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol


@dataclass
class LLMResponse:
    """Structured response from an LLM call, including token accounting."""

    content: dict
    """Parsed JSON response from the model."""

    input_tokens: int
    """Number of input tokens consumed by this call."""

    output_tokens: int
    """Number of output tokens generated by this call."""

    model: str
    """Model identifier that actually served the request."""

    raw_text: str
    """Raw text response before JSON parsing."""


class LLMClient(Protocol):
    """Protocol for LLM clients used by the insight (and future) stages.

    Implementations must provide both structured generation and embedding.
    """

    def generate_json(
        self,
        *,
        system: str,
        user: str,
        schema: dict,
        model: str,
        max_tokens: int = 1024,
    ) -> LLMResponse:
        """Generate a JSON response constrained to the given schema.

        Args:
            system: System prompt setting the task context.
            user: User prompt with the specific request.
            schema: JSON Schema dict constraining the output format.
            model: Model identifier to use for this call.
            max_tokens: Maximum output tokens.

        Returns:
            LLMResponse with parsed JSON content and token counts.
        """
        ...

    def embed(self, texts: list[str], *, model: str) -> list[list[float]]:
        """Produce embeddings for a batch of texts.

        Args:
            texts: Strings to embed.
            model: Embedding model identifier.

        Returns:
            List of embedding vectors, one per input text.
        """
        ...
